export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const ORDERS_SUCCESS = "ORDERS_SUCCESS";
export const ORDERS_FAIL = "ORDERS_FAIL";
export const CLEAR_OERRORS = "CLEAR_OERRORS";
export const CART_ORDERS = "CART_ORDERS";

export const UPDATE_FAIL = "UPDATE_FAIL";
export const ORDER_CANCELLED = "ORDER_CANCELLED";

export const REGISTERSELLER_SUCCESS = "REGISTERSELLER_SUCCESS";
export const REGISTERSELLER_FAIL = "REGISTERSELLER_FAIL";
export const SELLER_LOADED = "SELLER_LOADED";
export const AUTHSELLER_ERROR = "AUTHSELLER_ERROR";
export const LOGINSELLER_SUCCESS = "LOGINSELLER_SUCCESS";
export const LOGINSELLER_FAIL = "LOGINSELLER_FAIL";
export const LOGOUTSELLER = "LOGOUTSELLER";
export const SELLERS_RADIUS = "SELLERS_RADIUS";
